/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.gserv.collab.bot

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.modules.extra.phishing.DetectionAction
import com.kotlindiscord.kord.extensions.modules.extra.phishing.extPhishing
import me.gserv.collab.bot.extensions.GeneralExtension

suspend fun main() {
    val bot = ExtensibleBot(TOKEN) {
        applicationCommands {
            defaultGuild(GUILD_ID)
        }

        chatCommands {
            defaultPrefix = "?"
            enabled = true
        }

        extensions {
            add(::GeneralExtension)

            extPhishing {
                appName = "QuiltMC's Comfy (not Cozy) Bot"
                detectionAction = DetectionAction.LogOnly
                logChannelName = "phishing-logs"
                requiredCommandPermission = null

                check { isNotManager() }

                regex("([^\\s</]+\\s*(?:\\.|dot)+\\s*[^\\s>/]+)")
            }
        }
    }

    bot.start()
}
